service: covid-increment-sls
package:
  exclude:
    - README.md
custom:
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    TELEGRAM_TOKEN:
      prod: ${env:TELEGRAM_TOKEN}
      dev: ${env:TELEGRAM_TOKEN_DEV}


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    TELEGRAM_TOKEN: ${self:custom.myEnvironment.TELEGRAM_TOKEN.${self:custom.myStage}}

functions:
  covid:
    handler: handler.covidApp
    events:
      - http:
          path: covid
          method: post
	  cors: true
plugins:
  - serverless-offline
